services:
  app:
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
      - USERNAME=karlo
      - PASSWORD=12345
    volumes:
      - .:/var/www/notesapp
    ports:
      - "8380:80"