services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
      args:
          USER_ID: 1000
          GROUP_ID: 1000
    environment:
      - APP_ENV=dev
      - USERNAME=karlo
      - PASSWORD=12345
    volumes:
      - .:/var/www/notesapp
    ports:
      - "8380:8080"