services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
      args:
          USER_ID: 1000
          GROUP_ID: 1000
    environment:
      - APP_ENV=dev
      - PHP_CS_FIXER_IGNORE_ENV=1
      - AUTH_EMAIL=${AUTH_EMAIL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT=${GITHUB_REDIRECT}
    volumes:
      - .:/app
    ports:
      - "8380:8080"